[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[context.branch-deploy.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
